# Site settings
title: Cryptic Chat
email: dolphin@likethemammal.com
description: >
  We are a group of developers involved in the tech industry that work,
  laugh, discover, and grow together. We encourage each other to push the
  boundaries of the technology we work with everyday. To help reach our
  personal goals we collaborating often and want others to share in this 
  experience.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cryptic-io.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: :title/
paginate: 13


# Build settings
markdown: kramdown
